/*
 * This file was generated by the Gradle 'init' task.
 */

import org.gradle.internal.os.OperatingSystem

plugins {
    java
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://mvn.mchv.eu/repository/mchv/")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    // The telegram api lib dependencies
    val tdlightVersion = "2.8.1.2"
    val tdlightNativesVersion = "4.0.242"
    // Jar lib itself
    implementation("it.tdlight:tdlight-java:$tdlightVersion")
    // By-os native dependencies
    val os = OperatingSystem.current()
    when {
        os.isWindows -> implementation("it.tdlight:tdlight-natives-windows-amd64:$tdlightNativesVersion")
        os.isLinux   -> implementation("it.tdlight:tdlight-natives-linux-amd64:$tdlightNativesVersion")
        os.isMacOsX  -> implementation("it.tdlight:tdlight-natives-osx-amd64:$tdlightNativesVersion")
        // Sorry, aarch64 mac users, you will have to compile & provide the .so urselves
        // (from https://github.com/tdlight-team/tdlight)
    }

    // Lombok
    val lombokVersion = "1.18.20"
    implementation("org.projectlombok:lombok:$lombokVersion")

    // JQuery for frontend AJAX
    implementation("org.webjars:jquery:3.6.0")

    // Spring (boot)
    val springBootVersion = "2.4.5"
    implementation("org.springframework.boot:spring-boot-starter-web:$springBootVersion")
    implementation("org.springframework.boot:spring-boot-starter-security:$springBootVersion")
    implementation("org.springframework.boot:spring-boot-starter-validation:$springBootVersion")
    implementation("org.springframework.boot:spring-boot-starter-thymeleaf:$springBootVersion")

    // Spring/thymeleaf extensions
    implementation("org.thymeleaf.extras:thymeleaf-extras-springsecurity5:3.0.4.RELEASE")
    implementation("org.springframework.security:spring-security-taglibs:5.2.0.RELEASE")

    // Misc
    runtimeOnly("org.springframework.boot:spring-boot-devtools:$springBootVersion")
    testImplementation("org.springframework.boot:spring-boot-starter-test:$springBootVersion")
}

// Build config...

group = "space"
version = "0.0.1-SNAPSHOT"
description = "SeaSearch"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}
